package com.sample
 
import com.sample.DroolsTest.Message;
 
rule "Hello World1212"
    when
        m : Message( status == Message.HELLO, myMessage : message )
    then
        System.out.println( myMessage );
        m.setMessage( "Goodbye cruel world1212" );
        m.setStatus( Message.GOODBYE );
        update( m );
end

rule "GoodBye1212"
    when
        Message( status == Message.GOODBYE, myMessage : message )
    then
        System.out.println( myMessage );
end
